-- VER DATABASES DEFAULTS
SHOW DATABASES;

-- CRIAR DATABASE NOVO E VER ELE JUNTO COM OS DEFAULTS
                -- DATABASE
CREATE DATABASE DB;
SHOW DATABASES;

-- ACESSAR O DATABASE E CRIAR UMA TABLE
    # DATABASE
USE DB;
             -- TABLE NAME
CREATE TABLE T(
    # VALUES
    id INT PRIMARY KEY,
    name VARCHAR(100),
    value FLOAT
);

-- VER TABELA CRIADA
SHOW TABLES;
         -- TABLE
DESCRIBE T;

-- VER TODOS OS DADOS DA TABELA
              -- TABLE
SELECT * FROM T;

-- DELETAR TABLE E DATABASE
            -- TABLE
-- DROP TABLE T;
			   -- DATABASE
-- DROP DATABASE DB;
